language: python
python:
  - "2.7"
  - "3.5"
sudo: required
services:
  - docker
  
before_script:
  - docker pull scidash/scipy-notebook-plus
  - docker build . -t scidash/sciunit

script: 
  - docker run -it scidash/sciunit python -m unittest test_*